[colors-dark]
alpha=0.9
# alpha-mode=default # Can be `default`, `matching` or `all`
background=1a1b26
foreground=ffffff
# flash=7f7f
# flash-alpha=0.5

cursor=1d2021 1d2021
# Black
regular0=665c54
bright0=665c54
# Red
regular1=ea6962
bright1=ea6962
# Green
regular2=a9b665
bright2=a9b665
# Yellow
regular3=e78a4e
bright3=e78a4e
# Blue
regular4=7daea3
bright4=7daea3
# Magenta
regular5=d3869b
bright5=d3869b
# Cyan
regular6=89b482
bright6=89b482
# White
regular7=d4be98
bright7=d4be98
