general {
    lock_cmd = pidof hyprlock || hyprlock     # Avoid starting multiple instances of hyprlock
    before_sleep_cmd = loginctl lock-session  # Lock the session before the computer goes to sleep
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && pkill hyprsunset && hyprsunset # Turn the monitor back on after resuming
}

# Lock screen after 5 minutes (300 seconds)
#listener {
#    timeout = 150
#    on-timeout = loginctl lock-session
#}

# Turn off the monitor after 10 minutes (600 seconds)
listener {
    timeout = 300
    on-timeout = pkill hyprsunset && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && hyprsunset -g 100 -t 6500 
    ignore_inhibit = true
}
